#!/usr/bin/perl -w
# vim: set ts=4:
#
# List banned users.

use strict;

use DBI;
#my $db = 'apoeinfo_bbdev1';
my $db = 'apoeinfo_bb1';

use Config::Tiny;
my $Config = Config::Tiny->read("$ENV{HOME}/.config/dbi.conf");
my $C = $Config->{$db};

my $dbh = DBI->connect(
	"$C->{type}:database=$db:host=$C->{host}",$C->{user},$C->{pw},
	{AutoCommit=>1,RaiseError=>1,PrintError=>0}
);

my $sth = $dbh->prepare(qq{
	select user_id,username,user_email,user_regdate from phpbb_users where
		user_id in (select ban_userid from phpbb_banlist where ban_userid <> 0)
	order by user_regdate asc
});
$sth->execute();

print qq{"user_id","username","user_email","user_regdate"\n};
while (my $row = $sth->fetch) {
	printf qq{"$row->[0]","$row->[1]","$row->[2]","%4d-%02d-%02d"\n},
		(localtime($row->[3]))[5]+1900,
		(localtime($row->[3]))[4]+1,
		(localtime($row->[3]))[3]
	;
}

$sth->finish;
