#!/usr/bin/perl -w
# vim: set ts=4:
#
# List accounts that have not been used since creation as long as they are at least
# $Days_Since_Creation old.

use strict;

my $Days_Since_Creation = 30;
my $Seconds_Per_Day = 24*60*60;

use DBI;
#my $db = 'apoeinfo_bbdev1';
my $db = 'apoeinfo_bb1';

use Config::Tiny;
my $Config = Config::Tiny->read("$ENV{HOME}/.config/dbi.conf");
my $C = $Config->{$db};

my $dbh = DBI->connect(
	"$C->{type}:database=$db:host=$C->{host}",$C->{user},$C->{pw},
	{AutoCommit=>1,RaiseError=>1,PrintError=>0}
);

my $threshold_time = time - $Days_Since_Creation * $Seconds_Per_Day;
my $sth = $dbh->prepare(qq{
	select username,user_email,user_regdate,user_inactive_time from phpbb_users where
		user_ip <> '' and
		user_lastvisit = 0 and
		user_regdate < ?
	order by user_regdate asc
});
$sth->execute($threshold_time);

print qq{"username","user_email","user_regdate","confirmed?"\n};
while (my $row = $sth->fetch) {
	printf qq{"$row->[0]","$row->[1]","%4d-%02d-%02d","%s"\n},
		(localtime($row->[2]))[5]+1900,
		(localtime($row->[2]))[4]+1,
		(localtime($row->[2]))[3],
		$row->[3] ? 'N' : 'Y'
	;
}

$sth->finish;
